// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBdTFgkg7AtGa3qF3R4QxqoF6toyDcf1E',
    appId: '1:620882285358:web:718714a6dfbc12a191a0bf',
    messagingSenderId: '620882285358',
    projectId: 'stocks1-4f5b9',
    authDomain: 'stocks1-4f5b9.firebaseapp.com',
    databaseURL: 'https://stocks1-4f5b9-default-rtdb.firebaseio.com',
    storageBucket: 'stocks1-4f5b9.appspot.com',
    measurementId: 'G-B23KGBZLG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJ6PsAAz432_XnriWUMldkxPnJ4dRnn8',
    appId: '1:620882285358:android:8f0e9b896bce9d9491a0bf',
    messagingSenderId: '620882285358',
    projectId: 'stocks1-4f5b9',
    databaseURL: 'https://stocks1-4f5b9-default-rtdb.firebaseio.com',
    storageBucket: 'stocks1-4f5b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR0b0q9ed92TR7xjVEvp8vWD6bDzTqo-4',
    appId: '1:620882285358:ios:45484f58c418c1a591a0bf',
    messagingSenderId: '620882285358',
    projectId: 'stocks1-4f5b9',
    databaseURL: 'https://stocks1-4f5b9-default-rtdb.firebaseio.com',
    storageBucket: 'stocks1-4f5b9.appspot.com',
    iosBundleId: 'com.example.stocks1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR0b0q9ed92TR7xjVEvp8vWD6bDzTqo-4',
    appId: '1:620882285358:ios:f19dd1d27d595f6091a0bf',
    messagingSenderId: '620882285358',
    projectId: 'stocks1-4f5b9',
    databaseURL: 'https://stocks1-4f5b9-default-rtdb.firebaseio.com',
    storageBucket: 'stocks1-4f5b9.appspot.com',
    iosBundleId: 'com.example.stocks1.RunnerTests',
  );
}
